run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unconvert
    - unused
  disable-all: false

issues:
  exclude-dirs:
    - build
    - vendor
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
    - path: cmd/
      linters:
        - typecheck
    - path: test/
      linters:
        - typecheck
        - unused
  exclude:
    - "should have a package comment"
    - "exported .* should have comment or be unexported"
    - "import .* is a program, not an importable package"
    - "undefined: opml\\."
    - "could not load export data"
    - "no export data for"
